// AQUI VAI FICAR A TABELA LISTANDO OS ENTREGADORES
// VAI SER POSSIVEL VERIFICAR O STATUS DO ENTREGADOR
// POR EXEMPLO: DISPONIVEL, ENTREGANDO, EM COLETA E OFFLINE
// OS CAMPOS VÃO SER NOME, LOCALIZAÇÃO E STATUS. OS CAMPOS DEVEM SER ATUALIZADOS EM TEMPO REAL