// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtmtq4V6zhbDS7qJZH5Kz62z1uxsJ43LY',
    appId: '1:511904374346:web:118f8509b275fd4a7510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    authDomain: 'flutter-entregadev.firebaseapp.com',
    databaseURL: 'https://flutter-entregadev-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    measurementId: 'G-36Y568FQ3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzavBkt7euoR78rkpw2EmBz_qHlcK9FxE',
    appId: '1:511904374346:android:c73dd68620d898e37510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    databaseURL: 'https://flutter-entregadev-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd79AnnJjQKcAhWaMVc95FQU-b4Ui3w1w',
    appId: '1:511904374346:ios:c783b77ee34f41327510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    databaseURL: 'https://flutter-entregadev-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    iosBundleId: 'com.example.dashboardEntregasdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd79AnnJjQKcAhWaMVc95FQU-b4Ui3w1w',
    appId: '1:511904374346:ios:c783b77ee34f41327510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    databaseURL: 'https://flutter-entregadev-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    iosBundleId: 'com.example.dashboardEntregasdev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtmtq4V6zhbDS7qJZH5Kz62z1uxsJ43LY',
    appId: '1:511904374346:web:422cd804ce9da3bc7510b3',
    messagingSenderId: '511904374346',
    projectId: 'flutter-entregadev',
    authDomain: 'flutter-entregadev.firebaseapp.com',
    databaseURL: 'https://flutter-entregadev-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-entregadev.firebasestorage.app',
    measurementId: 'G-CWJGRVYKBC',
  );
}
